import { GetStaticProps, NextPage, GetStaticPaths } from 'next';
import { Comic, ComicData } from "dh-marvel/features/marvel/comic.types";
import { CardDetail } from "dh-marvel/components/ui/cardDetail/CardDetail";
import { getComic, getComics } from "dh-marvel/services/marvel/marvel.service";
import Head from 'next/head';
import BodySingle from 'dh-marvel/components/layouts/body/single/body-single';
import { useRouter } from 'next/router';

interface Props {
	comic: ComicData;
}


const ComicPage:NextPage<Props> = ({comic}) => {    

	return (   
        <>
        <Head>
            <title>DH-Marvel Store</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <BodySingle title={"Detalle"}>
					 <CardDetail data={comic} />
             </BodySingle>   
        </>
            );
};

export const getStaticPaths:GetStaticPaths = async () => {
	const res = await getComics()
    const comics = res?.data?.results || [];
     const paths = comics.map((comic:Comic) => ({
     params: { id: comic.id.toString() },
      }))      
  return { paths, fallback: false }
}


export const getStaticProps: GetStaticProps = async ({ params }) => {	
	const id= params?.id;
	try {
		const res = await getComic(`${id}`)     
		
		return {
			props: {
				comic:res,
			},
		};
	} catch (error) {
		console.error('No se pudo obtener el personaje', error);
		return {
			props: {
				comic: {},
			}
		}
	}
	
};

export default ComicPage;